# This workflow is adapted from:
# https://github.com/mvdan/github-actions-golang/blob/master/.github/workflows/test.yml

name: Test
permissions:
  contents: read
  pull-requests: read

on: [push, pull_request]

jobs:
  test-nocache:
    strategy:
      matrix:
        go-version: [1.25.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: false
    - run: go test ./...
